[general]
import = ["~/.config/alacritty/themes/themes/night_owlish_light.toml"]
live_config_reload = true

[colors.normal]
white = "#ffffff"

[font]
size = 12
glyph_offset = { x = 0, y = 0 }
offset = { x = 0, y = 0 }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }

[window]
decorations = "none"
dynamic_padding = true
startup_mode = "Maximized"

[keyboard]
bindings = [
    # Shift+Return sends ESC+Enter (same as Option+Enter) to work in tmux
    # source: https://www.reddit.com/r/ClaudeAI/comments/1m83if0/you_can_use_shiftenter_to_add_new_lines_in_claude/
    { key = "Return", mods = "Shift", chars = "\u001b\r" }
    #{ key = "Return", mods = "Shift", chars = "\n" }
]
