#####################
# Reference: https://github.com/alacritty/alacritty/blob/master/alacritty.yml
live_config_reload: true
window:
  dynamic_padding: true
  decorations: none
  decoration_theme_variant: dark
  startup_mode: Maximized

font:
  normal:
    family: monospace
    style: Regular
  bold:
    family: monospace
    style: Bold
  italic:
    family: monospace
    style: Italic
  size: 12
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

# Pop!_OS colors (custom)
colors:
  # Default colors
  primary:
    background: '#333333'
    foreground: '#F2F2F2'

  # Normal colors
  normal:
    black:   '#333333'
    red:     '#A04B50' #AE4B50
    green:   '#859000'
    yellow:  '#C4A000'
    blue:    '#3465A4'
    magenta: '#75507B'
    cyan:    '#06989A'
    white:   '#D3D7CF'

  # Bright colors
  bright:
    black:   '#88807C'
    red:     '#F15D22'
    green:   '#73C48F'
    yellow:  '#FFCE51'
    blue:    '#48B9C7'
    magenta: '#AD7FA8'
    cyan:    '#34E2E2'
    white:   '#EEEEEC'
