#####################
# Reference: https://github.com/alacritty/alacritty/blob/master/alacritty.yml
live_config_reload: true
window:
  dynamic_padding: true
  decorations: none
  startup_mode: Maximized

font:
  normal:
    family: monospace
    style: Regular
  bold:
    family: monospace
    style: Bold
  italic:
    family: monospace
    style: Italic
  size: 12
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

# See https://github.com/alacritty/alacritty-theme
import:
#  - ~/.config/alacritty/themes/themes/ayu_light.yaml
  - ~/.config/alacritty/themes/themes/papercolor_light.yaml
#  - ~/.config/alacritty/themes/themes/solarized_light.yaml
#  - ~/.config/alacritty/themes/themes/night_owlish_light.yaml

#  - ~/.config/alacritty/themes/themes/afterglow.yaml
#  - ~/.config/alacritty/themes/themes/argonaut.yaml
#  - ~/.config/alacritty/themes/themes/atom_one_light.yaml
#  - ~/.config/alacritty/themes/themes/ayu_dark.yaml
#  - ~/.config/alacritty/themes/themes/base16_default_dark.yaml
#  - ~/.config/alacritty/themes/themes/blood_moon.yaml
#  - ~/.config/alacritty/themes/themes/breeze.yaml
#  - ~/.config/alacritty/themes/themes/campbell.yaml
#  - ~/.config/alacritty/themes/themes/challenger_deep.yaml
#  - ~/.config/alacritty/themes/themes/citylights.yaml
#  - ~/.config/alacritty/themes/themes/Cobalt2.yaml
#  - ~/.config/alacritty/themes/themes/cyber_punk_neon.yaml
#  - ~/.config/alacritty/themes/themes/darcula.yaml
#  - ~/.config/alacritty/themes/themes/dark_pastels.yaml
#  - ~/.config/alacritty/themes/themes/doom_one.yml
#  - ~/.config/alacritty/themes/themes/dracula.yaml
#  - ~/.config/alacritty/themes/themes/everforest_dark.yml
#  - ~/.config/alacritty/themes/themes/everforest_light.yml
#  - ~/.config/alacritty/themes/themes/falcon.yaml
#  - ~/.config/alacritty/themes/themes/flat_remix.yml
#  - ~/.config/alacritty/themes/themes/gnome_terminal.yaml
#  - ~/.config/alacritty/themes/themes/gotham.yaml
#  - ~/.config/alacritty/themes/themes/gruvbox_dark.yaml
#  - ~/.config/alacritty/themes/themes/gruvbox_light.yaml
#  - ~/.config/alacritty/themes/themes/gruvbox_material.yml
#  - ~/.config/alacritty/themes/themes/high_contrast.yaml
#  - ~/.config/alacritty/themes/themes/horizon-dark.yaml
#  - ~/.config/alacritty/themes/themes/hyper.yaml
#  - ~/.config/alacritty/themes/themes/iterm.yaml
#  - ~/.config/alacritty/themes/themes/konsole_linux.yaml
#  - ~/.config/alacritty/themes/themes/low_contrast.yaml
#  - ~/.config/alacritty/themes/themes/material_theme.yaml
#  - ~/.config/alacritty/themes/themes/material_theme_mod.yaml
#  - ~/.config/alacritty/themes/themes/monokai_charcoal.yaml
#  - ~/.config/alacritty/themes/themes/monokai_pro.yaml
#  - ~/.config/alacritty/themes/themes/moonlight_ii_vscode.yaml
#  - ~/.config/alacritty/themes/themes/nord.yaml
#  - ~/.config/alacritty/themes/themes/oceanic_next.yaml
#  - ~/.config/alacritty/themes/themes/omni.yml
#  - ~/.config/alacritty/themes/themes/one_dark.yaml
#  - ~/.config/alacritty/themes/themes/palenight.yml
#  - ~/.config/alacritty/themes/themes/papercolor_dark.yaml
#  - ~/.config/alacritty/themes/themes/papertheme.yaml
#  - ~/.config/alacritty/themes/themes/pencil_dark.yaml
#  - ~/.config/alacritty/themes/themes/pencil_light.yaml
#  - ~/.config/alacritty/themes/themes/remedy_dark.yaml
#  - ~/.config/alacritty/themes/themes/rose-pine.yaml
#  - ~/.config/alacritty/themes/themes/seashells.yaml
#  - ~/.config/alacritty/themes/themes/smoooooth.yml
#  - ~/.config/alacritty/themes/themes/snazzy.yaml
#  - ~/.config/alacritty/themes/themes/solarized_dark.yaml
#  - ~/.config/alacritty/themes/themes/solarized_light.yaml
#  - ~/.config/alacritty/themes/themes/taerminal.yaml
#  - ~/.config/alacritty/themes/themes/tango_dark.yaml
#  - ~/.config/alacritty/themes/themes/tender.yaml
#  - ~/.config/alacritty/themes/themes/terminal_app.yaml
#  - ~/.config/alacritty/themes/themes/thelovelace.yaml
#  - ~/.config/alacritty/themes/themes/tokyo-night-storm.yaml
#  - ~/.config/alacritty/themes/themes/tokyo-night.yaml
#  - ~/.config/alacritty/themes/themes/tomorrow_night.yaml
#  - ~/.config/alacritty/themes/themes/tomorrow_night_bright.yaml
#  - ~/.config/alacritty/themes/themes/ubuntu.yaml
#  - ~/.config/alacritty/themes/themes/wombat.yaml
#  - ~/.config/alacritty/themes/themes/xterm.yaml
#  - ~/.config/alacritty/themes/themes/zenburm.yaml
