import = ["~/.config/alacritty/themes/themes/night_owlish_light.toml"]
live_config_reload = true

[colors.normal]
white = "#ffffff"

[font]
size = 12
glyph_offset = { x = 0, y = 0 }
offset = { x = 0, y = 0 }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }

[window]
#decorations = "none"
dynamic_padding = true
startup_mode = "Maximized"
